name: mon-portfolio
services:
  - name: backend
    git:
      branch: main
      repo_clone_url: "https://github.com/MARAMATA/portfolio_maramata.git"
    buildpacks:  # ✅ Ajout des buildpacks pour une détection correcte
      - "heroku/python"
    build_command: "cd backend && pip install -r requirements.txt"
    run_command: "cd backend && gunicorn --bind 0.0.0.0:5001 app:app"
    envs:
      - key: DATABASE_URL
        value: "postgresql+psycopg2://maramata:maramata@portfoliodb:5432/portfoliodb"
      - key: JWT_SECRET_KEY
        value: "33be23a8558808478c01430936a9a30b506ee2dd24b66da5c4c60db6f9a133d3"
      - key: SMTP_SERVER
        value: "smtp.gmail.com"
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        value: "maramatad@gmail.com"
      - key: SMTP_PASSWORD
        value: "yatmslxawsvwtzed"
      - key: ADMIN_EMAIL
        value: "maramatad@gmail.com"
    http_port: 5001
    routes:
      - path: "/api"  # ✅ Le backend sera accessible via /api

static_sites:
  - name: frontend
    git:
      branch: main
      repo_clone_url: "https://github.com/MARAMATA/portfolio_maramata.git"
    buildpacks:  # ✅ Ajout des buildpacks pour garantir la détection du frontend
      - "heroku/nodejs"
    build_command: "cd frontend && npm install && npm run build"
    output_dir: "frontend/build"
    routes:
      - path: "/"  # ✅ Le frontend sera accessible à la racine

databases:
  - name: portfoliodb  
    engine: POSTGRES  # ✅ DigitalOcean accepte "POSTGRES" en majuscules, pas "PG"
    version: "15"  # ✅ DigitalOcean ne supporte pas "17", on utilise "15"
    size: "db-s-1vcpu-1gb"
