name: mon-portfolio
services:
  - name: backend
    git:
      branch: main
      repo_clone_url: "https://github.com/MARAMATA/portfolio_md.git"
    # Se positionner dans le dossier backend avant d’installer et de lancer l’application
    build_command: "cd backend && pip install -r requirements.txt"
    run_command: "cd backend && gunicorn --bind 0.0.0.0:5001 app:app"
    envs:
      - key: DATABASE_URL
        value: "postgresql+psycopg2://maramata:maramata@portfolio_db:5432/portfolio_db"
      - key: JWT_SECRET_KEY
        value: "33be23a8558808478c01430936a9a30b506ee2dd24b66da5c4c60db6f9a133d3"
      - key: SMTP_SERVER
        value: "smtp.gmail.com"
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        value: "maramatad@gmail.com"
      - key: SMTP_PASSWORD
        value: "yatmslxawsvwtzed"
      - key: ADMIN_EMAIL
        value: "maramatad@gmail.com"
    http_port: 5001

static_sites:
  - name: frontend
    git:
      branch: main
      repo_clone_url: "https://github.com/MARAMATA/portfolio_md.git"
    build_command: "cd frontend && npm install && npm run build"
    output_dir: "frontend/build"

databases:
  - name: portfolio_db
    engine: pg
    version: "17"
    size: "db-s-1vcpu-1gb"

